### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by miakobchuk** [hlxsites/24petwatch#98]
Pages which currently don't need breadcrumbs (Avinash will be circling back with confirmation):
 
https://www.24petwatch.com/paid/membership
https://www.24petwatch.com/paid/lost-pet-protection 
https://www.24petwatch.com/paid/lost-pet-recovery
https://www.24petwatch.com/paid/membership-v2 (not live yet - publishing on Thursday May 2)
 
https://www.24petwatch.com/lost-pet-protection/lps-quote
https://www.24petwatch.com/ca/lost-pet-protection/lps-quote
 
https://www.24petwatch.com/lost-pet-protection/lpm-plus
https://www.24petwatch.com/ca/lost-pet-protection/lpm-plus
 
https://www.24petwatch.com/lost-pet-protection/annual-quote
 
https://www.24petwatch.com/lost-pet-protection/summary-quote
https://www.24petwatch.com/ca/lost-pet-protection/summary-quote
 
https://www.24petwatch.com/blog (and all the article pages)
https://www.24petwatch.com/ca/blog (and all the article pages)
 
https://www.24petwatch.com/lost-pet-protection/pawpack

**Comment by mikeweis** [comment]
Note that using the **Block Party** implementation of **[Breadcrumbs](https://www.aem.live/developer/block-collection/breadcrumbs)** requires integration with 24PetWatch's current implementation of the following:
* .../blocks/header/header.css
  * 24pw: https://github.com/hlxsites/24petwatch/blob/develop/blocks/header/header.css
  * BP: https://github.com/adobe/aem-block-collection/blob/main/blocks/header/header.css
* .../blocks/header/header.js
  * 24pw: https://github.com/hlxsites/24petwatch/blob/develop/blocks/header/header.js
  * BP: https://github.com/adobe/aem-block-collection/blob/main/blocks/header/header.js

**Comment by mikeweis** [comment]
Things to note:
* the Block Party implementation has code that does *more* than just the breadcrumbs.  So we will need to "stitch" the breadcrumb parts (both `.js` and `.css`) into the respective Pet Watch customized files.
* the Block Party implementation uses the existing navigation (`<nav>`) information that is present in the HTML to flesh out the crumbs.  If our `.../drafts/develop/*` Word documents use an incomplete/fake header, the breadcrumbs can easily reduce to looking like: `Home > Title of Current Page` (instead of `Home > Title of Grandparent Page > Title of Parent Page > Title of Current Page`) ... just FYI.

**Comment by mikeweis** [comment]
PR: https://github.com/hlxsites/24petwatch/pull/130

**Comment by mikeweis** [comment]
Done.
 * code merged: CSS + JS
* applicable documents updated & available on Sharepoint: US + CA
